CREATE TABLE notifications (id INTEGER PRIMARY KEY, tstamp DATETIME DEFAULT CURRENT_TIMESTAMP, ntype VARCHAR(12), message VARCHAR(64));
CREATE TABLE rooms (id INTEGER PRIMARY KEY, roomname VARCHAR(32), seats INTEGER);
