#!/bin/sh

# give write perms to httpd user on amtc-web data dirs
chown _www /etc/amtc-web /var/lib/amtc-web

# enable mod_php5 and mod_rewrite
perl -pi -e 's@#LoadModule php5_module@LoadModule php5_module@' /etc/apache2/httpd.conf
perl -pi -e 's@#LoadModule rewrite_module@LoadModule rewrite_module@' /etc/apache2/httpd.conf

# for httpd 2.4, assume no mod_access_compat
httpd -v | grep 'Apache/2.4' && perl -pi -e 'BEGIN{undef $/;} s@Order allow,deny\n\s+Allow from all@Require all granted@sm' /etc/amtc-web/amtc-web_httpd.conf
httpd -v | grep 'Apache/2.4' && perl -pi -e 'BEGIN{undef $/;} s@Order allow,deny\n\s+Deny from all@Require all denied@smg' /etc/amtc-web/amtc-web_httpd.conf 

apachectl restart

# fixme: handle already installed/upgrade?
launchctl enable system/ch.hacker.amtc-web
launchctl bootstrap system /Library/LaunchDaemons/ch.hacker.amtc-web.plist
launchctl kickstart -kp system/ch.hacker.amtc-web

